// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateFolderSource(arg1) {
  return window['go']['main']['App']['CreateFolderSource'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function GetCategory(arg1) {
  return window['go']['main']['App']['GetCategory'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListFolderByCategory(arg1) {
  return window['go']['main']['App']['ListFolderByCategory'](arg1);
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
