// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCategory(arg1:string):Promise<models.Category>;

export function CreateFolderSource(arg1:number):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteFolder(arg1:number):Promise<void>;

export function GetCategory(arg1:number):Promise<models.Category>;

export function Greet(arg1:string):Promise<string>;

export function ListCategories():Promise<Array<models.Category>>;

export function ListFolderByCategory(arg1:number):Promise<Array<models.Folder>>;

export function ListFolders():Promise<Array<models.Folder>>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
